export const ru = {
  screens: {
    Language: {
      title: 'Здравствуйте!',
      description: 'Выберите язык приложения!',
      btn: 'Продолжить',
      nameScreen: 'Язык',
    },
    Auth: {
      nameScreen: 'Авторизация',
      description: 'У вас нет аккаунта?',
      linkDescription: 'Зарегистрироваться',
      email: 'Почта',
      password: 'Пароль',
      btn: 'Войти',
      errors: {
        passwordLengthLong: 'Максимальная длина пароля 30 символов',
        passwordLengthShort: 'Минимальная длина пароля 6 символов',
        passwordRequired: 'Поле пароль обязательно',
        emailRequired: 'Поле email обязательно',
        emailIncorrect: 'Некорректный Email',
        3024: 'Неверный логин и/или пароль',
      },
    },
    Theme: {
      nameScreen: 'Тема',
      title: 'На чьей ты стороне?',
      description: 'Выберите тему приложения!',
      btn: 'Продолжить',
      dark: 'Темная',
      light: 'Светлая',
      default: 'Системная',
    },
    Notification: {
      title: 'Хотите получать уведомления?',
      description: 'Разрешите уведомления',
      btn: 'Далее',
    },
    NotificationSetting: {
      nameScreen: 'Уведомления',
      noPushStatus: 'Предоставьте приложению разрешение на отправку уведомлений',
      noPushStatusLink: 'Перейти в настройки',
      Thresholds: 'Падение хешрейта до',
      Fluctuation: 'Изменение хешрейта',
      'Active workers': 'Активные воркеры',
      AlertSetting: 'Настройки уведомлений',
      modalName: 'Изменения настроек',
      modalBtn: 'Подтвердить',
      errors: {
        11001: 'No hashrate found, notification unavailable',
      },
    },
    LanguagesSettings: {
      nameScreen: 'Язык',
    },
    Settings: {
      nameScreen: 'Настройки',
      readFaq: 'Перейти в FAQ',
      accountLabel: 'Аккаунт',
      emailLabel: 'Почта',
      passwordLabel: 'Пароль',
      logout: 'Выйти',
      referal: 'Реферальная программа',
      support: 'Помощь',
      theme: 'Тема',
      language: 'Язык',
      passcode: 'Безопасность',
      notifications: 'Уведомления',
      mining: 'Настройки майнинга',
      tabName: {
        account: 'Аккаунт',
        general: 'Общие',
      },
    },
    AccessSecureCode: {
      title: 'Вам важна безопасность?',
      description: 'Установите код доступа',
      btn: 'Установить',
    },
    SecureCodeScreen: {
      nameScreen: 'Код доступа',
      exit: 'Выйти',
      authBimetricTitle: 'Вход в Trustpool',
      enterCode: 'Код доступа',
      repeatCode: 'Повторите код',
      skip: 'Не сейчас',
      resetPassCodeTitle: 'Сброс кода доступа',
      resetPassCodeDescription: 'Нажмите Ок чтобы сбросить код доступа и перейти на страницу авторизации',
      setCode: 'Установите новый код доступа',
      requestBioDescription: 'Нажмите Ок чтобы разрешить аутентификацию по {{type}}',
      errorNoRightCode: 'Неверный код. Осталось попыток: {{repeatCount}}',
      notRightCodeTitle: 'Неправильный код',
      notMatch: 'Не совпадает',
      cancel: 'Отмена',
      Fingerprint: 'отпечаток',
      'Face ID': 'Face ID',
      'Touch ID': 'Touch ID',
      // eslint-disable-next-line max-len
      notRightCodeDescription: 'Вы ввели некорректный код 5 раз, сейчас вы будете перенаправлены на страницу авторизации',
    },
    SecureStoreSettings: {
      nameScreen: 'Безопасность',
      usePasscode: 'Использовать код доступа',
      useBio: 'Использовать {{type}}',
      changePassCode: 'Изменить код доступа',
    },
    Support: {
      nameScreen: 'Помощь',
      stratum: "Stratum URL's",
      referal: 'Реферальная ссылка',
      telegramm: 'Перейти в Telegram',
      faq: 'Перейти в FAQ',
    },
    StratumUrls: {
      nameScreen: "Stratum URL's",
    },
    RefferalList: {
      nameScreen: 'Реферальная ссылка',
    },
    ChangePassword: {
      nameScreen: 'Изменение пароля',
      newPassword: 'Новый пароль',
      repeatPassword: 'Повторите пароль',
      btnStepOne: 'Продолжить',
      btnStepTwo: 'Подтвердить',
      oldPassword: 'Текущий пароль',
      titleRequiredPass: 'Обязательное поле',
      titleRepeatPass: 'Пароли не совпадают',
      GA: 'GA код',
      requiredOldPass: 'Обязательное поле',
      reqeiredValuedGA: 'Обязательное поле',
      errors: {
        4014: 'Некорректный GA код',
        4011: 'Некорректный GA код',
        3023: 'Пожалуйста установите новый пароль',
        3022: 'Не верный текущий пароль',
        4: 'Слишком часто',
      },
    },
    Home: {
      nameScreen: 'Главная',
      accountsModalTitle: 'Выберите аккаунт',
      accountModalBackBtn: 'Выбор',
      accountAddModalTitle: 'Создать субаккаунт',
      modalChangeAccountInputLabel: 'Имя субаккаунта',
      modalChangeAccountBtn: 'Подтвердить',
      balance: 'Баланс аккаунта',
      paymentTotal: 'Всего выплачено',
      earningTotal: 'Общий доход',
      coinModalTitle: 'Валюта',
      currencyModalTitle: 'Валюта',
      calculationDiff: 'Сложность',
      widgetCalculation: 'Калькулятор',
      widgetWorkersTitle: 'Воркеры',
      chartTitle: 'График хешрейта',
      widgetWorkers: {
        active: 'Активные',
        unactive: 'Неактив.',
        total: 'Всего',
      },
      widgetChart: {
        '10-min': '10 минут',
        '1-hour': '1 час',
        '1-day': '1 день',
      },
      errors: {
        3013: 'Пользователь с таким именем уже существует',
        3010: 'Недопустимое имя субаккаунта',
      },
    },
    MiningScreen: {
      nameScreen: 'Майнинг',
      btn: 'Изменить {{coinPoint}} адрес',
      btnPayment: 'Изменить минимальную выплату',
      modalChangePayment: 'Минимальную выплату',
      paymentTime: 'Время выплат',
      currentPaymentStep: 'Размер минимальной выплаты',
      address: '{{coinPoint}} адрес',
      errors: {
        11001: 'Хешрейт не найдем, уведомления не доступны',
      },
    },
    Payment: {
      nameScreen: 'Начисления',
      tabName: {
        payment: 'Выплаты',
        earning: 'Доходы',
      },
      status: {
        paid: 'Выплачено',
        unknown: 'Неизвестно',
      },
      date: 'Время платежа',
      statusDetail: 'Состояние',
      value: 'Сумма платежа',
      adress: 'Адрес платежа',
      transaction: 'Транзакция',
      havntAdress: 'У вас нет адреса выплат',
      clickToSet: 'Нажмите сюда, чтобы его установить',
      havntPayment: 'У вас пока нет выплат',
      havntPaymentHow: 'Как настроить майнинг ферму?',
      earning: {
        date: 'Дата',
        totalProfit: 'Общий доходы',
        hashrate: 'Хэшрейт',
        unitOutput: 'Unit output ({{prefix}}H/s)',
        startTime: 'Время начала',
        endTime: 'Время конца',
        profit: 'Доход',
        score: 'Балл',

      },
    },
    Calculation: {
      nameScreen: 'Калькулятор',
      title: 'Значение хешрейта:',
      textHelp: 'Введите значение',
      resultTitle: 'Результат за',
      helpDescription: 'Приблизительная доходность основанная на данных за 7 дней, с учетом комиссии пула 1%',
      time: {
        hour: 'Час',
        day: 'День',
        week: 'Недел{{ending}}',
        month: 'Месяц',
      },
    },
    Workers: {
      nameScreen: 'Воркеры',
      tabsName: {
        active: 'Активные',
        unActive: 'Неактив.',
        all: 'Все',
      },
      lastSubmit: 'Последняя активность',
      hourAvg: 'За час',
      minAvg: 'За 10 минут',
      dayAvg: 'За день',
      search: 'Поиск по группе {{name}}',
      searchAll: 'Поиск',
      sort: 'Сортировка',
      reset: 'Сброс',
      sortList: {
        name: 'Имя',
        hashrate: 'Хешрейт',
        lastActive: 'Последняя активность',
      },
      group: {
        modalHeader: 'Выберите группу',
        allWorkers: 'Все воркеры',
        defaultWorkers: 'По умолчанию',
        deleteConfirmTitle: 'Напоминание',
        modalHeaderRight: 'Ред.',
        modalHeaderLeft: 'Готово',
        // eslint-disable-next-line max-len
        deleteConfirmText: 'Воркеры из удаляемой группы будут перенесены в группу по умолчанию. Продолжить удаление группы воркеров?',
        deleteConfirmBtnYes: 'Принять',
        deleteConfirmBtnNo: 'Отмена',
        deleteConfirmBtnNo1: 'Отм.',
        empty: 'Группа пуста \n Выберите другую группу или',
        goToAllWorkers: 'Перейти ко всем воркерам',
        badSearch: 'Воркеры по запросу не найдены',
        createGroup: {
          header: 'Создать группу',
          label: 'Имя группы',
          headerRename: 'Изменить имя',
          btn: 'Принять',
        },
        errors: {
          5007: 'Группа воркеров существует',
        },
        more: 'Ещё',
        selectAll: 'Выделить всё',
        unSelectAll: 'Снять выделение',
        moveSelectedTo: 'Переместить выбранные',
        moveTo: 'Переместить',
      },
      havntWorkers: {
        ACTIVE: 'Активные воркеры не найдены',
        INACTIVE: 'Неактивные воркеры не найдены',
        ALL: 'Воркеры не найдены. \n Нужна помощь по настройке нового воркера?',
      },
      info: {
        mainTextFirstStr: 'Создайте воркера вида',
        mainTextFirstBold: '«UserID.workerID»',
        mainTextSecondStr: 'и любой пароль',
        // eslint-disable-next-line max-len
        mainTextMiddle: 'для него. WorkerID должен состоять из цифр и строчных букв длиной не более 64 символов. Например, если Ваш идентификатор пользователя - miner, название воркера',
        mainTextFourthStr: 'может быть',
        mainTextSecondBold: '«miner.001»',
        mainTextLastString: 'Пароль не обязателен.',
        firstLinkLabel: 'Stratum URL 1',
        secondLinkLabel: 'Stratum URL',
        note: 'Примечание. Порт',
        available: 'тоже доступен.',
        forAllUrlsEng: '',
        forAllUrls: 'Для всех URL.',
        showMore: 'Подробнее',
        showLess: 'Скрыть',
      },
      modal: {
        title: 'Stratum URL',
      },
    },
    Referals: {
      nameScreen: 'Реферальная награда',
      headerTitle: 'Реферальная награда',
      headerBackText: 'Главная',
      tabName: {
        myReferrals: 'Список рефералов',
        rewardList: 'Список наград',
      },
      textFirstStr: 'Пригласите друга в Trustpool',
      textSecondStrStart: 'и получайте от',
      textPercent: '0.3%',
      textSecondStrEnd: 'за его/ee доход',
      textThirdStr: 'от майнинга в качестве вознаграждения.',
      linkLabel: 'Ваша реферальная ссылка',
      mention: 'Ваша ссылка скопирована в буфер обмена',
      isRewardListEmpty: 'Награды не найдены. У ваших рефералов еще нет доходов',
      dayAvg: 'Хэшрейт за день',
      referralRatio: 'Ставка',
      reward: 'Награда',
      hashrate: 'Хэшрейт',
      modal: {
        title: 'Реферальная ссылка',
        referralRules: 'Реферальные правила:',
        // eslint-disable-next-line max-len
        firstRule: 'Только пользователи, которые подписываются по ВАШЕЙ реферальной ссылке, считаются ВАШИМИ рефералами.',
        // eslint-disable-next-line max-len
        secondRule: 'Награды зачисляются на ваш счет в 08:30 (UTC + 8) следующего дня. Возможна задержка платежа.',
        thirdRule: 'Пожалуйста, обратитесь к веб-сайту, чтобы узнать фактическое соотношение рефералов.',
      },
    },
    DetailWorker: {
      nameScreen: '{{workerNumber}}',
      lastSubmit: 'Последняя активность:',
      status: 'Статус:',
      active: 'Активный',
      unactive: 'Неактивный',
      rejectRate: 'Reject rate:',
      '10minAvg': 'Среднее за 10 минут:',
      '1hourAvg': 'Среднее за час:',
      '1dayAvg': 'Среднее за день:',
    },
    BottomNav: {
      nameScreen: 'Главная',
    },
    Menu: {
      nameScreen: 'Меню',
    },
    PaymentDetails: { nameScreen: 'Выплата' },
    SetPaymentAdress: {
      nameScreen: '{{coin}} адрес',
      verificate: 'Код подтверждения отправлен на e-mail \nПожалуйста, проверьте почтовый ящик',
      verificateCode: 'Верификационный код',
      verificateGaCode: 'Двухфакторный код',
      continueBtn: 'Продолжить',
      resendCode: 'Отправить заново',
      sec: 'сек',
      setAddress: '{{coin}} адрес',
      fillAddress: 'Введите адрес выплат',
      set: 'Установить',
      errors: {
        4033: 'Верификация не пройдена',
        8004: 'Неверный адрес выплат',
        405: 'Время ожидания вышло',
        required: 'Верификационный код обязательное поле',
      },
    },
    ThemeSetting: {
      nameScreen: 'Тема',
    },
  },
  Chart: {
    click: 'Активируйте нажатием',
    hour: 'Среднее за час',
    min: 'Среднее за 10 минут',
    day: 'Среднее за день',
    rejectRate: 'Reject rate',
    hashRate: 'Хешрейт',
    Workers: 'Воркеры',
  },
  Pachal: {
    title: 'Поздравляем!',
    // eslint-disable-next-line max-len
    text: 'Вы на половине пути к победе!\n Сделайте скриншот этого экрана и отправьте его в Telegram чат Trustpool.\n Первый участник, решивший секрет приложения и приславший скриншот с этим сообщением в чат, становится победителем!',
  },
  languageText: 'Русский',
  disconnectOne: 'Отсутствует подключение к интернету',
  disconnecTwo: 'Часть функций может быть недоступна',
};
